
[workspace]
resolver = "2"
members = [
    "ch01/_2_hello_cargo",
    "ch02/_1_guessing_game",
    "ch03/_1_variables", "ch03/_2_data_types", "ch03/_3_functions", "ch03/_4_comments", "ch03/_5_control_flow", "ch03/_exercise", "ch04/_1_ownership"]
